import type { ModelProvidersConfig } from './config.js';

export const exampleModelProvidersConfig: ModelProvidersConfig = {
  providers: [
    {
      id: 'deepseek',
      displayName: 'DeepSeek',
      baseURL: 'https://api.deepseek.com',
      apiKey: process.env['DEEPSEEK_API_KEY'] ?? '',
      isDefault: true,
    },
    {
      id: 'openai',
      displayName: 'OpenAI',
      baseURL: 'https://api.openai.com',
      apiKey: process.env['OPENAI_API_KEY'] ?? '',
    },
    {
      id: 'anthropic',
      displayName: 'Anthropic',
      baseURL: 'https://api.anthropic.com',
      apiKey: process.env['ANTHROPIC_API_KEY'] ?? '',
    },
  ],
  models: [
    {
      id: 'deepseek-chat',
      provider: 'deepseek',
      displayName: 'DeepSeek Chat',
      complexity: 'light',
      specialties: ['chat', 'general'],
      contextWindow: 64000,
      maxOutputTokens: 4096,
      pricingPer1kInput: 0.0014,
      pricingPer1kOutput: 0.0028,
    },
    {
      id: 'deepseek-reasoner',
      provider: 'deepseek',
      displayName: 'DeepSeek Reasoner',
      complexity: 'heavy',
      specialties: ['reasoning'],
      contextWindow: 64000,
      maxOutputTokens: 4096,
      pricingPer1kInput: 0.004,
      pricingPer1kOutput: 0.016,
    },
    {
      id: 'gpt-4o',
      provider: 'openai',
      displayName: 'GPT-4o',
      complexity: 'heavy',
      specialties: ['chat', 'reasoning', 'vision'],
      contextWindow: 128000,
      maxOutputTokens: 16384,
      pricingPer1kInput: 0.005,
      pricingPer1kOutput: 0.015,
    },
    {
      id: 'gpt-4o-mini',
      provider: 'openai',
      displayName: 'GPT-4o Mini',
      complexity: 'light',
      specialties: ['chat'],
      contextWindow: 128000,
      maxOutputTokens: 16384,
      pricingPer1kInput: 0.00015,
      pricingPer1kOutput: 0.0006,
    },
    {
      id: 'claude-sonnet-4-20250514',
      provider: 'anthropic',
      displayName: 'Claude Sonnet 4',
      complexity: 'heavy',
      specialties: ['chat', 'reasoning', 'vision', 'writing'],
      contextWindow: 200000,
      maxOutputTokens: 64000,
      pricingPer1kInput: 0.003,
      pricingPer1kOutput: 0.015,
    },
  ],
};
